vars:
  - article_classification_pwr_2022/config.py:TrainingConfig

stages:
  preprocess:
    foreach:
      - dataset: train
        file: ${TrainingConfig.processed_train}
      - dataset: validation
        file: ${TrainingConfig.processed_val}
      - dataset: test
        file: ${TrainingConfig.processed_test}
    do:
      cmd: python -m article_classification_pwr_2022.preprocessing.preprocess --dataset ${item.dataset} --output-file ${item.file}
      outs:
        - ${item.file}
